### ISSUE TITLE
No available releases for several years

### ISSUE THREAD

**Issue by ManiaSonicRUS** [AvalonBar/AvalonBar#12]
It's not really an issue, but I'd really like to test this kind of software as I'm really into getting different Longhorn stuff back to modern Windows (like Slate theme, I ported it myself) but there are literally no releases on GitHub.
So can you actually post a compiled release for me? Don't know how to contact you, it's very only way I got in mind

**Comment by fofajardo** [comment]
@ManiaSonicRUS I haven't had the motivation to work on this project and there's still a lot more work to do, which should explain the lack of releases. That said, here's a compiled release build that should work on HiDPI screens:
[AvalonBar-1.0.0.0a1.zip](https://github.com/AvalonBar/AvalonBar/files/10517584/AvalonBar-1.0.0.0a1.zip)

**Comment by ideapc** [comment]
> 

Thank you. I tested it and it works really nice, even though it has some issues with stability. But that's not a thing that I can complain of, as it's actually amazing overall.
I hope you'll continue working on it so it works even better and also hides itself when there is a borderless fullscreen app focused.
Also some showcase for other people who finds that (as you didn't provide any screenshots)
![image](https://user-images.githubusercontent.com/77688386/215264169-554ef38b-ab01-438f-ad8e-3b7c95f1c144.png)
