### ISSUE TITLE
sidebar appearing in video player when full screen

### ISSUE THREAD

**Issue by GhanzidkarGhanzer** [AvalonBar/AvalonBar#16]
so if you check "keep the sidebar on top of windows" then in video player in full screen it will appear so i would like for this to be fixed

**Comment by fofajardo** [comment]
Thanks for reporting! This is a known issue. Duplicate of #9.

**Comment by GhanzidkarGhanzer** [comment]
> Thanks for reporting! This is a known issue. Duplicate of #9.

ok but did you see the another issue i posted
